# Generated by Django 6.0.5 on 2026-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, db_column='Student_name', max_length=50, null=True)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=50, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=20, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
    ]
