# Generated by Django 6.0.5 on 2026-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(db_column='Admin_ID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True, unique=True)),
                ('contact', models.BigIntegerField(blank=True, db_column='Contact', null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
    ]
