# Generated by Django 6.0.5 on 2026-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admission_no', models.CharField(db_column='Admission_No', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=5, null=True)),
                ('father_name', models.CharField(blank=True, db_column='Father_Name', max_length=30, null=True)),
                ('mother_name', models.CharField(blank=True, db_column='Mother_Name', max_length=30, null=True)),
                ('father_occupation', models.CharField(blank=True, db_column='Father_Occupation', max_length=25, null=True)),
                ('mother_occupation', models.CharField(blank=True, db_column='Mother_Occupation', max_length=25, null=True)),
                ('father_contact', models.BigIntegerField(blank=True, db_column='Father_Contact', null=True)),
                ('mother_contact', models.BigIntegerField(blank=True, db_column='Mother_Contact', null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], db_column='Gender', max_length=10, null=True)),
                ('house', models.CharField(blank=True, db_column='House', max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_column='Blood_Group', max_length=5, null=True)),
                ('mode_of_transport', models.CharField(blank=True, db_column='Mode_of_Transport', max_length=20, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
