# Generated by Django 6.0.5 on 2026-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(db_column='Staff_ID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True, unique=True)),
                ('contact', models.BigIntegerField(blank=True, db_column='Contact', null=True)),
                ('qualifications', models.CharField(blank=True, db_column='Qualifications', max_length=100, null=True)),
                ('experience', models.CharField(blank=True, db_column='Experience', max_length=50, null=True)),
                ('subject', models.CharField(blank=True, db_column='Subject', max_length=20, null=True)),
                ('class_field', models.IntegerField(blank=True, db_column='Class', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], db_column='Gender', max_length=6, null=True)),
                ('role', models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Accountant', 'Accountant'), ('Receptionist', 'Receptionist'), ('Other', 'Other')], db_column='Role', max_length=20, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
    ]
