# Generated by Django 6.0.5 on 2026-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=10, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=5, null=True)),
                ('post_date', models.DateField(blank=True, db_column='Post_Date', null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('post_by_name', models.CharField(blank=True, db_column='Post_by_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
    ]
