# Generated by Django 6.0.5 on 2026-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('class_field', models.IntegerField(db_column='Class', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'fee_details',
                'managed': False,
            },
        ),
    ]
