# Generated by Django 6.0.5 on 2026-09-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.CharField(db_column='Guardian_ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True, unique=True)),
                ('contact', models.BigIntegerField(blank=True, db_column='Contact', null=True)),
                ('occupation', models.CharField(blank=True, db_column='Occupation', max_length=20, null=True)),
                ('relation', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father')], db_column='Relation', max_length=10, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
            ],
            options={
                'db_table': 'guardian',
                'managed': False,
            },
        ),
    ]
