# Generated by Django 6.0.5 on 2026-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('marks_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, db_column='Student_name', max_length=100, null=True)),
                ('term', models.CharField(blank=True, db_column='Term', max_length=50, null=True)),
                ('subject', models.CharField(blank=True, db_column='Subject', max_length=100, null=True)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=50, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=20, null=True)),
                ('marks_obt', models.DecimalField(blank=True, db_column='Marks_obt', decimal_places=2, max_digits=5, null=True)),
                ('total_marks', models.DecimalField(blank=True, db_column='total_Marks', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'marks',
                'managed': False,
            },
        ),
    ]
