# Generated by Django 6.0.5 on 2026-09-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classteacher',
            fields=[
                ('class_number', models.IntegerField(blank=True, db_column='Class_Number', null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=5, null=True)),
                ('class_teacher_name', models.CharField(blank=True, db_column='Class_teacher_name', max_length=100, null=True)),
                ('staff_id', models.CharField(db_column='Staff_ID', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'classteacher',
                'managed': False,
            },
        ),
    ]
