# Generated by Django 6.0.5 on 2026-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, db_column='Student_name', max_length=100, null=True)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=50, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=20, null=True)),
                ('deposit_date', models.DateField(blank=True, db_column='Deposit_date', null=True)),
                ('deposit_amount', models.DecimalField(blank=True, db_column='Deposit_amount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'fees_status',
                'managed': False,
            },
        ),
    ]
